apiVersion: v1
kind: ConfigMap
metadata:
  name: toml-config
  namespace: saga-oradb
data:
  teq.toml: |-
    #!/bin/bash 
    cd /tmp
    git clone https://github.com/ilfur/saga-oradb-k8s
    cp -R saga-oradb-k8s/dbscripts/* /projects
    rm -rf saga-oradb-k8s
