apiVersion: observability.oracle.com/v1alpha1
kind: DatabaseObserver
metadata:
  name: pdb1-observer
  namespace: saga-oradb
spec:
  database:
    dbUser:
      key: "sysadmin_user"
      secret: aipdb-secret

    dbPassword:
      key: "sysadmin_pwd"
      secret: aipdb-secret

    dbConnectionString:
      key: "connection1"
      secret: aipdb-secret


  exporter:
    image: "container-registry.oracle.com/database/observability-exporter:1.3.0"
    service:
      port: 9161
    configuration:
      configmap:
        key: "teq.toml"
        configmapName: "toml-config"
       
  prometheus:
    port: metrics
    labels:
      cdb: ai23-remote-cdb
      pdb: sagapdb1

  replicas: 1
---
apiVersion: observability.oracle.com/v1alpha1
kind: DatabaseObserver
metadata:
  name: pdb2-observer
  namespace: saga-oradb
spec:
  database:
    dbUser:
      key: "sysadmin_user"
      secret: aipdb-secret

    dbPassword:
      key: "sysadmin_pwd"
      secret: aipdb-secret

    dbConnectionString:
      key: "connection2"
      secret: aipdb-secret

  exporter:
    image: "container-registry.oracle.com/database/observability-exporter:1.3.0"
    service:
      port: 9161
    configuration:
      configmap:
        key: "teq.toml"
        configmapName: "toml-config"

  prometheus:
    port: metrics
    labels:
      cdb: ai23-remote-cdb
      pdb: sagapdb2

  replicas: 1
---
apiVersion: observability.oracle.com/v1alpha1
kind: DatabaseObserver
metadata:
  name: pdb3-observer
  namespace: saga-oradb
spec:
  database:
    dbUser:
    dbUser:
      key: "sysadmin_user"
      secret: aipdb-secret

    dbPassword:
      key: "sysadmin_pwd"
      secret: aipdb-secret

    dbConnectionString:
      key: "connection3"
      secret: aipdb-secret


  exporter:
    image: "container-registry.oracle.com/database/observability-exporter:1.3.0"
    service:
      port: 9161
    configuration:
      configmap:
        key: "teq.toml"
        configmapName: "toml-config"

  prometheus:
    port: metrics
    labels:
      cdb: ai23-remote-cdb
      pdb: sagapdb3

  replicas: 1
