CREATE PUBLIC DATABASE LINK PDB1_LINK CONNECT TO pdb_adm IDENTIFIED BY pdb_adm USING 'sagapdb1';
CREATE PUBLIC DATABASE LINK PDB2_LINK CONNECT TO pdb_adm IDENTIFIED BY pdb_adm USING 'sagapdb2';
CREATE PUBLIC DATABASE LINK PDB3_LINK CONNECT TO pdb_adm IDENTIFIED BY pdb_adm USING 'sagapdb3';

