ALTER SESSION SET PDB_FILE_NAME_CONVERT='/opt/oracle/oradata/SAGADB/pdbseed/','/opt/oracle/oradata/SAGADB/sagapdb2/';

CREATE PLUGGABLE DATABASE sagapdb2 ADMIN USER pdb_adm IDENTIFIED BY BrunhildeZ32##;

ALTER PLUGGABLE DATABASE sagapdb2 OPEN READ WRITE;

ALTER PLUGGABLE DATABASE sagapdb2 SAVE STATE;

ALTER SESSION SET PDB_FILE_NAME_CONVERT='/opt/oracle/oradata/SAGADB/pdbseed/','/opt/oracle/oradata/SAGADB/sagapdb3/';

CREATE PLUGGABLE DATABASE sagapdb3 ADMIN USER pdb_adm IDENTIFIED BY BrunhildeZ32##;

ALTER PLUGGABLE DATABASE sagapdb3 OPEN READ WRITE;

ALTER PLUGGABLE DATABASE sagapdb3 SAVE STATE;
